XCF-1964 Fix problem with applying patches to DB
Applying patches failed with the following error:
Failed to execute:  insert into patch (name) values ('unmanaged-to-acme')
org.postgresql.util.PSQLException: ERROR: duplicate key violates unique constraint "patch_pkey"

It was caused by a copy-and-paste error in database.xml - 'localization-fix' patch was marked with 'unmanaged-to-acme' name.


git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@11297 ab1d8caa-1f67-47f1-9e81-24633a41865c